name: wechat_kit
description: A powerful Flutter plugin allowing developers to auth/share/pay with natvie Android & iOS Wechat SDKs.
version: 1.1.2
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/wechat_kit

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  convert: ^2.0.2
  crypto: ^2.0.6

  uuid: '>=1.0.0 <3.0.0'

  json_annotation: '>=2.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  image: ^2.0.7

  path: ^1.6.4
  path_provider: ^1.4.0

  okhttp_kit: ^1.0.0

  pedantic:

  build_runner:
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: io.github.v7lin.wechat_kit
        pluginClass: WechatKitPlugin
      ios:
        pluginClass: WechatKitPlugin
